// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxRGw-xwKVw0HiITcjBOYfA-13xdFTj5s',
    appId: '1:105804718316:web:05c3b6e3d76ed6306605c9',
    messagingSenderId: '105804718316',
    projectId: 'demoapp-4c714',
    authDomain: 'demoapp-4c714.firebaseapp.com',
    storageBucket: 'demoapp-4c714.appspot.com',
    measurementId: 'G-Z2VJNPSYR2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCePg3PH0XhKAkP4tepZjWCq-YOJaZYd-I',
    appId: '1:105804718316:android:204eae4e3ccdcb956605c9',
    messagingSenderId: '105804718316',
    projectId: 'demoapp-4c714',
    storageBucket: 'demoapp-4c714.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQg7NxELkR-RjmmNFh6lepPT86bjoRg2c',
    appId: '1:105804718316:ios:ded5308a2e72de2d6605c9',
    messagingSenderId: '105804718316',
    projectId: 'demoapp-4c714',
    storageBucket: 'demoapp-4c714.appspot.com',
    iosBundleId: 'com.example.evcar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQg7NxELkR-RjmmNFh6lepPT86bjoRg2c',
    appId: '1:105804718316:ios:229249bd464debf66605c9',
    messagingSenderId: '105804718316',
    projectId: 'demoapp-4c714',
    storageBucket: 'demoapp-4c714.appspot.com',
    iosBundleId: 'com.example.evcar.RunnerTests',
  );
}
